### ISSUE TITLE
CE2: Scaffolding

### ISSUE THREAD

**Issue by CharlotteRuth** [sagekg/Grinnell-Computational-Physics#5]
I wonder if more instruction should be given to the students about how their code should look. For instance, should they be asked to write a function that takes certain inputs and has certain returns? I also wonder if modifiable template code to create the figures with the charges should be given to them.

**Comment by sagekg** [comment]
My thinking was that the examples for the streamplot and quiver plot would serve as templates for making the figures. I just copied that out of my code, so it should be pretty direct to use. I just added in the line to add the charge point to those (I think I wrote those before I was plotting the charges).

As for instruction, in my mind it makes sense to leave it pretty open-ended. They already have the code for the plots, so it works out to <40 lines of new code to calculate the whole vector field. But I think it would make sense to have some more instructions or suggestions about how to write the code, so I can add that.

I'm a little hesitant to scaffold too much, since I think more scaffolding means less problem-solving, but I'm happy to make it more closed if you think that's the way to go.
